//
// Created by gusdak on 8/27/17.
//

#ifndef INC_100_DAYS_OF_ALGORITHMS_DAY_18_ROOTSOFPOLYNOMIAL_HPP
#define INC_100_DAYS_OF_ALGORITHMS_DAY_18_ROOTSOFPOLYNOMIAL_HPP

#endif //INC_100_DAYS_OF_ALGORITHMS_DAY_18_ROOTSOFPOLYNOMIAL_HPP
